
# Site settings
title: "moofy.org"
domain: moofy.org
baseurl: "/"
url: "https://moofy.org"
github_source_link: "https://github.com/mufaro3/mufaro3.github.io"

# disqus
disqus_shortname: moofydotorg

# messages of the day
motds: [
  # 1984
  'WAR IS PEACE!',
  'IGNORANCE IS STRENGTH!',
  'FREEDOM IS SLAVERY!',

  # Slaughterhouse-Five
  'So it goes.'
]

footer_quotes: [
  # Nirvana
  "Forever in debt to your priceless advice",

  # Lain
  "Close the world, open the next",

  # Radiohead
  "That's it sir? You're leaving?",

  # The Smiths
  "Please excuse me from gym, I have a terrible cold coming on."
]

# Personal Information
public_email: 'mail <span class="normal">at</span> moofy <span class="normal">dot</span> org'
github: 'mufaro3'
current_book:
  title: "The Beautiful and Damned"
  author: "Scott Fitzgerald"

# Blog Settings

# Build settings
markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
permalink: /posts/:title/
safe: false
